go_import_path: github.com/sbueringer/kubectl-openstack-plugin

sudo: required
dist: trusty

env:
  global:
  - BAZEL_VERSION="0.16.1"

before_script:
- wget "https://storage.googleapis.com/bazel-apt/pool/jdk1.8/b/bazel/bazel_${BAZEL_VERSION}_amd64.deb"
- sudo dpkg --force-all -i bazel_${BAZEL_VERSION}_amd64.deb
- sudo apt-get install moreutils -y

script:
- bazel build //cmd:cmd
- go test -race -coverprofile=coverage.txt -covermode=atomic

cache:
  directories:
  - $HOME/.bzrepos


after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- cp bazel-bin/cmd/linux_amd64_pure_stripped/cmd /tmp/kubectl-os

deploy:
- provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file: /tmp/kubectl-os
  overwrite: true
  skip_cleanup: true
  on:
    tags: true