
sudo: required
dist: trusty

script:
- ./build.sh


before_deploy:
- cp ./kubectl-openstack /tmp/kubectl-openstack

deploy:
- provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
  - /tmp/kubectl-openstack
  overwrite: true
  skip_cleanup: true
  on:
    tags: true