apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: os
spec:
  version: "v0.0.6"
  platforms:
    - selector:
        matchExpressions:
          - {key: os, operator: In, values: [linux]}
      uri: https://github.com/sbueringer/kubectl-openstack-plugin/releases/download/v0.0.6/kubectl-os.tar.gz
      sha256: 52b0e3aee5226fd6f0bc75fe5a8d778c9ce12bd82380cd85074aa92ebe8fa035
      files:
        - from: "/kubectl-os"
          to: "."
      bin: "./kubectl-os"
  shortDescription: Extends kubectl with some OpenStack commands
  caveats: |
    This plugin only works with Kubernetes clusters running on OpenStack.
    Also the environment has to be set up as described here:
    https://github.com/sbueringer/kubectl-openstack-plugin
  description: |
    This plugin adds a few additional commands to kubectl to query for
    OpenStack objects. This of course only makes sense if the Kubernetes
    cluster is running on Openstack and the user has access to OpenStack
    credentials. Some of these commands are:

    # Shows PersistentVolumes joined with the corresponding OpenStack disks
    kubectl os volumes

    # Shows Services joined with the corresponding OpenStack LBaaS objects
    kubectl os lb

    # Show Nodes joined with the corresponding OpenStack servers
    kubectl os server
